[package]
name = "nargo-core"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[features]
default = []
serde = ["dep:serde"]

[dependencies]
anyhow.workspace = true
serde = { workspace = true, optional = true }
