[package]
name = "nargo-resolve"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
nargo-core = { path = "../nargo-core", features = ["serde"] }

assert-json-diff.workspace = true
lexopt.workspace = true
serde.workspace = true
serde_json.workspace = true
