[package]
name = "nargo-rustc"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
nargo-core = { path = "../nargo-core" }

anyhow.workspace = true
lexopt.workspace = true
semver.workspace = true
