[package]
name = "nargo-metadata"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
pico-args.workspace = true
semver = { version = "1", features = ["serde"] }
serde.workspace = true
serde_json.workspace = true
