name: CI

on:
  push:
  pull_request:
  merge_group:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref_name }}"
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  rust-lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just
      - uses: Swatinem/rust-cache@v2
      - run: just rust-lint --locked -- -D warnings
      - run: just rust-test --locked
      - run: just nargo-metadata-check

  rust-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just
      - run: just rust-fmt-check

  just-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just
      - run: just just-fmt-check

  bash-fmt-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just
      - uses: DeterminateSystems/nix-installer-action@main
      - run: just bash-fmt-check
      - run: just bash-lint

  nix-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just
      - uses: DeterminateSystems/nix-installer-action@main
      - run: just nix-fmt-check

  nix-build-gha:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: just nix-build-gha-ci
